[BFTokenDefinitions]
DataPointerIncrement = "a"
DataPointerDecrement = "c"

IncrementCellValue = "e"
DecrementCellValue = "i"

WriteCharacter = "j"
ReadCharacter = "o"

LoopBegin = "p"
LoopEnd = "s"

Delimiter = ""