[BFTokenDefinitions]
DataPointerIncrement = ">"
DataPointerDecrement = "<"

IncrementCellValue = "+"
DecrementCellValue = "-"

WriteCharacter = "."
ReadCharacter = ","

LoopBegin = "["
LoopEnd = "]"

Delimiter = ""